const emojis = {
  a: ["🅰️", "🌲", "⛵", "#avengers.jpg"],
  b: ["🅱️️", "⏳", "#boston.jpg"],
  c: ["©️", "🌜", "☪"],
  d: ["👌", "🌛", "#detroit.png"],
  e: ["📧", "#internet.png"],
  f: ["f", "🎏", "#facebook.png"],
  g: ["g", "#gatsby.jpg", "#georgia.png"],
  h: ["🏨", "🇭", "♓"],
  i: ["ℹ️", "🚶‍♂️", "🚶‍♀️", "🕴"],
  j: ["🐋", "🌶", "🍶"],
  k: ["🇰"],
  l: ["💪", "🛴"],
  m: ["Ⓜ️", "〽", "#michigan.png", "#mail.png", "#mediacurrent.png"],
  n: ["♑️", "#netscape.gif"],
  o: [
    "📀",
    "⚽️",
    "🐽",
    "🐡",
    "🍩",
    "🍪",
    "#poke.png",
    "#spin.gif",
    "#drupal.png",
  ],
  p: ["🅿️", "#flag.png"],
  q: ["🇶", "🍳", "🍭"],
  r: ["®️"],
  s: ["💲", "⚡️"],
  t: ["✝️", "#axe.png"],
  u: ["🤘", "#urock.png"],
  v: ["✌", "♈️", "🖖", "#vim.png"],
  w: ["🔱", "📛", "#washington.jpg", "#wordpress.png"],
  x: ["✖️", "#xjira.png"],
  y: ["🍸", "🤸‍♀️", "🤸‍♂️"],
  z: ["🇿", "🐍"],
}

export default emojis
